apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: mypyapp
        image: coffeepay/mypyapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
