apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  namespace: customer-dev
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: proddstrainingrcaq.azurecr.io/mypyapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
